/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import * as components from "../../models/components";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class StockUpdateResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * An unknown error occurred interacting with the API.
     */
    @SpeakeasyMetadata()
    error?: components.ErrorT;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}

export class StockUpdateRequestBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "drink" })
    @Type(() => components.DrinkInput)
    drink?: components.DrinkInput;

    @SpeakeasyMetadata()
    @Expose({ name: "ingredient" })
    @Type(() => components.IngredientInput)
    ingredient?: components.IngredientInput;
}
