/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import * as components from "../../models/components";
import { AxiosResponse } from "axios";

export class CreateOrderRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "request, media_type=application/json",
        elemType: components.OrderInput,
    })
    requestBody: components.OrderInput[];

    /**
     * The url to call when the order is updated.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=callback_url" })
    callbackUrl?: string;
}

export class CreateOrderResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * An unknown error occurred interacting with the API.
     */
    @SpeakeasyMetadata()
    error?: components.ErrorT;

    /**
     * The order was created successfully.
     */
    @SpeakeasyMetadata()
    order?: components.Order;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;
}
